### PR TITLE
Fix issue no services shown & Add tip when there is no available service

### PR DESCRIPTION
**Pull request by edwardwang0302**
Fix issue no services shown & Add tip when there is no available service

### CODE REVIEW

**Comment by kalyanmulampaka** [comment]
Can you merge and release the fix? Thanks

**Comment by edwardwang0302** [comment]
@kalyanmulampaka I commit my pull request 15 days ago, but the master hasn't accepted my pr. I can't merge and release the patch, cause I'm not the master

**Comment by coreyjackwilson** [comment]
I have rebuilt and verified this fix @aderyabin can you approve?

**Comment by aderyabin** [comment]
@coreyjackwilson @kalyanmulampaka @edwardwang0302 Thanks!

**Pull request merged**
